//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVaLi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebBanVaLiEntities : DbContext
    {
        public WebBanVaLiEntities()
            : base("name=WebBanVaLiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAnhSP> tAnhSP { get; set; }
        public virtual DbSet<tChatLieu> tChatLieu { get; set; }
        public virtual DbSet<tDanhMucSP> tDanhMucSP { get; set; }
        public virtual DbSet<tHangSX> tHangSX { get; set; }
        public virtual DbSet<tKichThuoc> tKichThuoc { get; set; }
        public virtual DbSet<tLoaiDT> tLoaiDT { get; set; }
        public virtual DbSet<tLoaiSP> tLoaiSP { get; set; }
        public virtual DbSet<tQuocGia> tQuocGia { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
